name: Snake Animation Updater
on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:      

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write  

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Create output directory
        run: mkdir -p output

      - name: Generate Snake
        run: |
          curl -s "https://github-contribution-svg.vercel.app/api?user=${{ github.repository_owner }}&type=snake&random=$RANDOM" > output/github-contribution-grid-snake.svg
          curl -s "https://github-contribution-svg.vercel.app/api?user=${{ github.repository_owner }}&type=snake&palette=github-dark&random=$RANDOM" > output/github-contribution-grid-snake-dark.svg

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/
          git commit -m "Update snake animation [skip ci]" || echo "No changes to commit"
          git push
