name: Generate Snake SVG

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: pip install requests

    - name: Generate snake.svg
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GH_USER: KWas866
      run: python3 snake.py

    - name: Commit and push snake.svg
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add snake.svg
        git commit -m "Update snake.svg from GitHub Actions [skip ci]" || echo "No changes to commit"
        git push origin main
