name: Generate Snake SVG

on:
  schedule:
    - cron: '0 0 * * *'   
  workflow_dispatch: {}   
permissions:
  contents: write  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run snake generator
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  
          GH_USER: KWas866                   
        run: |
          python3 snake.py

      - name: Commit and push SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add snake.svg
          if ! git diff --staged --quiet; then
            git commit -m "chore: update snake.svg (auto)"
            git push
          else
            echo "No changes to commit"
          fi
